name: Health Check

on:
  schedule:
    - cron: '34 * * * *'

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check application health
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://slinzhq-fso-pokedex.onrender.com/health
